using System;
using System.Collections.Generic;

namespace lab_2 {

    public class Data {
        public static List<Animal> animals = new List<Animal>(){
            new Animal("Chicken", "Antony", 83),
            new Animal("Horse", "Cherry", 73),
            new Animal("Cow", "Anna", 14),
            new Animal("Horse", "Emma", 4),
            new Animal("Cow", "Terry", 38),
            new Animal("Chicken", "Terry", 66),
            new Animal("Horse", "Anna", 5),
            new Animal("Chicken", "Cherry", 57),
            new Animal("Duck", "Antony", 44),
            new Animal("Horse", "Emma", 2),
            new Animal("Horse", "Antony", 32),
            new Animal("Duck", "Antony", 93),
            new Animal("Chicken", "Terry", 15),
            new Animal("Cow", "Anna", 11),
            new Animal("Chicken", "Antony", 27),
            new Animal("Cow", "Andrew", 55),
            new Animal("Chicken", "Andrew", 71),
            new Animal("Chicken", "Emma", 33),
            new Animal("Cow", "Emma", 89),
            new Animal("Chicken", "Terry", 25),
            new Animal("Chicken", "Andrew", 81),
            new Animal("Horse", "Emma", 42),
            new Animal("Cow", "Cherry", 71),
            new Animal("Chicken", "Anna", 0),
            new Animal("Cow", "Antony", 9),
            new Animal("Duck", "Terry", 9),
            new Animal("Chicken", "Antony", 13),
            new Animal("Duck", "Anna", 70),
            new Animal("Chicken", "Anna", 49),
            new Animal("Duck", "Antony", 47),
            new Animal("Horse", "Andrew", 5),
            new Animal("Duck", "Antony", 41),
            new Animal("Chicken", "Andrew", 53),
            new Animal("Duck", "Emma", 55),
            new Animal("Duck", "Terry", 40),
            new Animal("Cow", "Emma", 45),
            new Animal("Horse", "Cherry", 83),
            new Animal("Duck", "Emma", 66),
            new Animal("Horse", "Antony", 52),
            new Animal("Horse", "Anna", 20),
            new Animal("Duck", "Anna", 26),
            new Animal("Horse", "Antony", 63),
            new Animal("Duck", "Cherry", 10),
            new Animal("Cow", "Cherry", 92),
            new Animal("Cow", "Antony", 44),
            new Animal("Cow", "Terry", 75),
            new Animal("Chicken", "Cherry", 86),
            new Animal("Horse", "Anna", 77),
            new Animal("Cow", "Andrew", 23),
            new Animal("Chicken", "Anna", 99),
            new Animal("Duck", "Andrew", 36),
            new Animal("Chicken", "Emma", 18),
            new Animal("Chicken", "Cherry", 60),
            new Animal("Duck", "Anna", 27),
            new Animal("Chicken", "Cherry", 97),
            new Animal("Duck", "Andrew", 51),
            new Animal("Horse", "Cherry", 35),
            new Animal("Duck", "Anna", 22),
            new Animal("Chicken", "Emma", 97),
            new Animal("Chicken", "Cherry", 19),
            new Animal("Chicken", "Cherry", 84),
            new Animal("Horse", "Anna", 46),
            new Animal("Cow", "Andrew", 51),
            new Animal("Chicken", "Andrew", 43),
            new Animal("Horse", "Cherry", 82),
            new Animal("Cow", "Anna", 19),
            new Animal("Duck", "Anna", 98),
            new Animal("Cow", "Andrew", 21),
            new Animal("Cow", "Terry", 36),
            new Animal("Horse", "Emma", 4),
            new Animal("Horse", "Anna", 0),
            new Animal("Chicken", "Antony", 21),
            new Animal("Chicken", "Andrew", 76),
            new Animal("Cow", "Antony", 1),
            new Animal("Duck", "Emma", 26),
            new Animal("Duck", "Cherry", 29),
            new Animal("Chicken", "Anna", 20),
            new Animal("Duck", "Anna", 88),
            new Animal("Horse", "Cherry", 37),
            new Animal("Cow", "Antony", 67),
            new Animal("Horse", "Antony", 23),
            new Animal("Chicken", "Terry", 48),
            new Animal("Chicken", "Anna", 14),
            new Animal("Cow", "Terry", 44),
            new Animal("Chicken", "Andrew", 36),
            new Animal("Duck", "Anna", 22),
            new Animal("Duck", "Anna", 49),
            new Animal("Horse", "Anna", 25),
            new Animal("Duck", "Antony", 11),
            new Animal("Horse", "Andrew", 71),
            new Animal("Duck", "Anna", 76),
            new Animal("Horse", "Antony", 93),
            new Animal("Duck", "Cherry", 91),
            new Animal("Duck", "Antony", 88),
            new Animal("Horse", "Anna", 58),
            new Animal("Duck", "Antony", 39),
            new Animal("Cow", "Andrew", 92),
            new Animal("Horse", "Anna", 75),
            new Animal("Horse", "Terry", 68),
            new Animal("Duck", "Cherry", 61),
        };
    }

    public class Animal {
        public string type;
        public string name;
        public int age;

        public Animal(string type, string name, int age) {
            this.type = type;
            this.name = name;
            this.age = age;
        }
    }
}